// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpISwxEuTtMqgARAN5mO6sDZuHtKmJ-o',
    appId: '1:300130516629:web:34c3f559f8e517a9ad259c',
    messagingSenderId: '300130516629',
    projectId: 'pooja-cb29e',
    authDomain: 'pooja-cb29e.firebaseapp.com',
    storageBucket: 'pooja-cb29e.appspot.com',
    measurementId: 'G-EP9WYMCLP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVrd3rfgvlH78cSPa4hW1HmFBoXMdW9A',
    appId: '1:300130516629:android:a0c7036dc99ae82bad259c',
    messagingSenderId: '300130516629',
    projectId: 'pooja-cb29e',
    storageBucket: 'pooja-cb29e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADEnZ76Ga2jDFSi2jkNXNGGQDzKzxAV1E',
    appId: '1:300130516629:ios:7f64493043907db1ad259c',
    messagingSenderId: '300130516629',
    projectId: 'pooja-cb29e',
    storageBucket: 'pooja-cb29e.appspot.com',
    iosBundleId: 'com.example.poojaForEveryone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADEnZ76Ga2jDFSi2jkNXNGGQDzKzxAV1E',
    appId: '1:300130516629:ios:7f64493043907db1ad259c',
    messagingSenderId: '300130516629',
    projectId: 'pooja-cb29e',
    storageBucket: 'pooja-cb29e.appspot.com',
    iosBundleId: 'com.example.poojaForEveryone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBpISwxEuTtMqgARAN5mO6sDZuHtKmJ-o',
    appId: '1:300130516629:web:8a90d98905363a7dad259c',
    messagingSenderId: '300130516629',
    projectId: 'pooja-cb29e',
    authDomain: 'pooja-cb29e.firebaseapp.com',
    storageBucket: 'pooja-cb29e.appspot.com',
    measurementId: 'G-LMX2G6VPN5',
  );

}